version: 2
registries:
  bit-components:
    type: npm-registry
    url: https://node.bit.dev
    token: ${{secrets.BIT_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - bit-components
    schedule:
      interval: "daily"
    groups:
      showoff-scope-dependencies:
         patterns:
           - "@showoff*"
