version: 2
registries:
  bit-components:
    type: npm-registry
    url: https://node-registry.bit.cloud
    token: ${{secrets.BIT_TOKEN}}
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - bit-components
    schedule:
      interval: "daily"
    versioning-strategy: lockfile-only
    groups:
      showoff-scope-dependencies:
         patterns:
           - "@showoff*"
